[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "migrations"]
  include_ext = ["go"]
  kill_delay = "2s"
  rerun = false

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
