Log:
  Level: info
  Formatter:
    Format: text

Port: 8080
ExternalDomain: localhost
ExternalPort: 8080
ExternalSecure: false

TLS:
  Enabled: false

Database:
  Postgres:
    Host: postgres
    Port: 5432
    Database: zitadel
    MaxOpenConns: 20
    MaxIdleConns: 10
    MaxConnLifetime: 30m
    MaxConnIdleTime: 5m
    User:
      Username: postgres
      Password: postgres
      SSL:
        Mode: disable
    Admin:
      Username: postgres
      Password: postgres
      SSL:
        Mode: disable

DefaultInstance:
  Language: pt
  Org:
    Name: Nutrometra Internal
